# Generated by Django 4.2.28 on 2026-02-18 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_note', models.TextField(blank=True, help_text='Note for the pharmacist')),
                ('pharmacist_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('administered', 'Administered'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_sessions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, max_length=200)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_entries', to='pharmacy.drug')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='records.administrationsession')),
            ],
        ),
    ]
